### PR TITLE
subTreeLike and everySubTreeLike methods

### PR DESCRIPTION
**Pull request by hartzis**
Added `subTreeLike` and `everySubTreeLike` methods and tests. https://github.com/glenjamin/skin-deep/issues/9#issuecomment-144347882

Solves #22.

### CODE REVIEW

**Comment by donabrams** [comment]
Why is 'isLike' a string instead of a boolean?

**Comment by glenjamin** [comment]
`isLike` is a string because I hate seeing mysterious booleans at the call site.

```
funcCall(true)
// vs
funcCall('isLike')
```

Bit busy this weekend so proper review might be Monday, looks good at first glance though :+1:

**Comment by hartzis** [comment]
I did the `isLike` because i saw the use of 'one' here https://github.com/glenjamin/skin-deep/blob/master/skin-deep.js#L211

I could also see using an options object instead, maybe
`createFinder(query, predicate, {'isLike': true});`

But then you'd probably need to default options to an empty object.

**Comment by glenjamin** [comment]
Released as `v0.12.0`

**Pull request merged**
