### PR TITLE
Added dive()

### LINKED ISSUE #20: Need ability to render sub tree
```js
function renderedSubTree(paths, tree, context) {
  while (paths.length) {
    var path = paths.shift();
    var rawTree = tree.subTree(path);
    if (!rawTree) throw new Error(`${path} not found in ${tree}`);
    var node = rawTree.getRenderOutput();
    tree = skinDeep.shallowRender(
      () => React.createElement(node.type, node.props),
      context
    );
  }
  return tree;
}
```

### PR DESCRIPTION
**Pull request by hoegrammer**
and tests. However, could not work out how to test that the context parameter is utilised correctly

closes #20

### CODE REVIEW

**Comment by glenjamin** [comment]
LGTM, perhaps `expandSubTree` as the name, so it's more clearly an action? Did anyone else weigh in on the name?

To test the context thing, you'd need to add `contextTypes` to a child, and `childContextTypes` + `getChildContext` to a parent.

**Comment by glenjamin** [comment]
Latest plan is to call this `.dive()` I think?

**Comment by hoegrammer** [comment]
Yes. 

I wonder what happens when there are multiple subcomponents of same type

**Comment by glenjamin** [comment]
Oh, good point. Might need a more expressive API for selecting the component to dive into.

**Comment by hoegrammer** [comment]
Decision made to traverse first component in lists rather than trying to return all or specify (for now, anyway)

**Pull request merged**
