### PR TITLE
Add [attr] and [attr="val"] to findNode capabilities

### PR DESCRIPTION
**Pull request by donabrams**
Added support for `tree.findNode('[data-has-tests="yay"]')`. Tests added and passing.

### CODE REVIEW

**Comment by glenjamin** [comment]
Ooo, this is quite nice - but I'm not sure if it'll be needed once we do the API changes discussed in https://github.com/glenjamin/skin-deep/issues/9#issuecomment-145968740 land - what do you think?

**Comment by donabrams** [comment]
#9 will definitely solve this case. ETA?

**Comment by glenjamin** [comment]
I meant to do it last weekend - so should be soon.

**Comment by glenjamin** [comment]
I've published `v0.9.0` which allows you to pass props as the second argument of `subTree` and `everySubTree`.

Along with the `findComponent` and `findComponentLike` functions this should cover the functionality in this PR - let me know if you need more in the short term.

**Comment by donabrams** [comment]
Awesome, thanks!

**Comment by donabrams** [comment]
Hmm, I don't necessarily want to have to specify the Component Name, just filter based on props. Context: we're using skin deep to get coverage and verify behavior but NOT tie ourselves to html structure/presentation (classes/ids). So really, this would be our ideal API:

```
tree.findNode({'data-testref': 'good'})
tree.everySubTree({'data-testref': /.*good./*/})
tree.findComponentLike({'data-testref': 'yay green'}, { children: ['Navigation', {'data-testref': 'fly'}] })
```

**Comment by glenjamin** [comment]
Ah, I see - could you live with `*` as the first argument?

**Comment by donabrams** [comment]
Yeah, definitely could do that.

**Comment by glenjamin** [comment]
Released `*` in `subTree` and `everySubTree` as `v0.11.0`.

Haven't added to other methods as they're all going away soonish.

**Comment by donabrams** [comment]
Goooood.... GOOOOOOOOD... Now all we gotta do is write a ton of tests!

**Pull request closed without merging**
